{% set name = "hydrosignatures" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cf6f5a4bce78534b8fe1f6a3549da8c38dbd9ea4d75143957a08b338e07dc963

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=3.9
    - numpy >=2
    - pandas >=1.0
    - scipy
    - xarray >=2023.03.0

test:
  imports:
    - hydrosignatures
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/hydrosignatures
  summary: A collection of tools for computing hydrological signatures
  license: MIT
  license_file: LICENSE
  doc_url: https://docs.hyriver.io/

extra:
  recipe-maintainers:
    - cheginit
